### ISSUE TITLE
after-build issue with latest simplecov

### ISSUE THREAD

**Issue by Yanchek99** [paambaati/codeclimate-action#102]
Odd behaviors happening with latest simplecov, seems like an issue getting the committed at timestamp which seems unrelated to the simplecov update but wanted to mention just incase.

SimpleCov version 0.18.2

CI Code
```
- name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID:  foobar
        with:
          coverageCommand: bundle exec rails test
          debug: true
```

Error
```
./cc-reporter after-build --exit-code 0 --debug
time="2020-02-14T19:14:44Z" level=debug msg="about to run format-coverage" 
time="2020-02-14T19:14:44Z" level=debug msg="searching for a formatter to use" 
time="2020-02-14T19:14:44Z" level=debug msg="checking coverage.py formatter" 
time="2020-02-14T19:14:44Z" level=debug msg="checking search path coverage.xml for coverage.py formatter" 
time="2020-02-14T19:14:44Z" level=debug msg="checking lcov formatter" 
time="2020-02-14T19:14:44Z" level=debug msg="checking search path coverage/lcov.info for lcov formatter" 
time="2020-02-14T19:14:44Z" level=debug msg="checking simplecov formatter" 
time="2020-02-14T19:14:44Z" level=debug msg="checking search path coverage/.resultset.json for simplecov formatter" 
time="2020-02-14T19:14:44Z" level=debug msg="found file coverage/.resultset.json for simplecov formatter" 
time="2020-02-14T19:14:44Z" level=debug msg="couldn't load committed at from ENV, trying git..." 
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
```

**Comment by davehenton** [comment]
Hi @Yanchek99 , 

Dave here with Code Climate. Unfortunately, Code Climate's test reporter isn't compatible with the latest version of SimpleCov. We're actively in touch with the maintainers, and we hope to resolve this in the near future. You can keep track of our progress here: https://github.com/codeclimate/test-reporter/issues/413

For now, the simplest solution is for you to revert back to your previous version of SimpleCov.

**Comment by Yanchek99** [comment]
Hey @davehenton, Thanks for quickly commenting on this.  I can rollback SimpleCov for now not a problem.  I will close this in favor of the other issue.

Thanks again.
