### ISSUE TITLE
Request: v1, v2 major-version branches

### ISSUE THREAD

**Issue by jasonkarns** [paambaati/codeclimate-action#142]
GitHub Actions recommends (and the community has a convention) that a vN branch exists that always points to the latest minor/patch release for a given major release line. This way users can receive patch and minor updates without continually bumping their workflow manifests.

Some docs mention using a tag for this ref; but that's not really recommended practice since it runs counter to git's expectation that tags do not move; so I'd recommend using a branch. FWIW, I keep my branch up-to-date using a release workflow to advance the vN branch on each tagged release: https://github.com/nodenv/actions/blob/3f3fd551a5416f6d792793a826fadb713b376cea/.github/workflows/release.yml#L14-L23

**Comment by stevenharman** [comment]
I just hit this same thing - expecting `uses: paambaati/codeclimate-action@v2` to grab the latest 2.x series. Instead the run failed with 

```console
Error: Unable to resolve action `paambaati/codeclimate-action@v2`, unable to find version `v2`
```

It would be great to keep with [expected and recommended norms for versioning](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-versioned-actions).

_Sidebar_: Of course my buddy @jasonkarns hit this nearly a year before I did. 😉

**Comment by paambaati** [comment]
PRs welcome!

**Comment by jasonkarns** [comment]
@paambaati it's not possible for outside contributors to create a branch on your repo
