### ISSUE TITLE
Wrong commit SHA

### ISSUE THREAD

**Issue by andreipislariu** [paambaati/codeclimate-action#148]
Hi,

I trigger the tests and the coverage by pull request. When I check in Code Climate, I do see the right name, but not the right commit sha.

Based on what the great google says: 

"When the action is triggered by a pull_request event, GitHub will squash and merge this branch with the base branch, generating a new commit, thus a new hash.
The commit we want (the HEAD in the branch we're merging) can be fetched by running git rev-parse origin/$GITHUB_HEAD_REF."

**Comment by andreipislariu** [comment]
actually, I think that this issue has been solved in 2.5.6, but I cannot check it, because I have the same error as: https://github.com/paambaati/codeclimate-action/issues/119

**Comment by paambaati** [comment]
@andreipislariu #119 has now been fixed in [`v2.5.7`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.5.7).
