### ISSUE TITLE
Question: Is coverageCommand required if coverage has already been created?

### ISSUE THREAD

**Issue by awentzel** [paambaati/codeclimate-action#160]
**Is your feature request related to a problem? Please describe.**
I'm already running code coverage via `lerna run test --stream` and the documentation is not clear if `coverageCommand` is required on my monorepository if `/coverage` has already been created.

**Describe the solution you'd like**
The `coverageCommand` should be optional.

**Describe alternatives you've considered**
1. Add a script command for code coverage across 20+ packages

**Comment by paambaati** [comment]
@awentzel The `coverageCommand` is optional, and defaults to `yarn coverage` if not given. This is documented (see https://github.com/paambaati/codeclimate-action#inputs).
