### ISSUE TITLE
Run a gradle command as a coverageCommand

### ISSUE THREAD

**Issue by igorbiscanin** [paambaati/codeclimate-action#164]
I am trying to run a gradle tasks as coverageCommand, but the task is not found.

Here is my config:

```
- name: Generate and publish code coverage
uses: paambaati/codeclimate-action@v2.5.7
env:
# Set CC_TEST_REPORTER_ID as secret of your repo
CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
with:
coverageCommand: ./gradlew jacocoTestReport
# The report file must be there, otherwise Code Climate won't find it
coverageLocations:
"${{github.workspace}}/src/app/build/reports/coverage/staging/debug/report.xml::jacoco"
```

Is there an option to set a working directory or something. Any hints/leads what am I doing wrong.

**Comment by paambaati** [comment]
@igorbiscanin Please follow the issue template and include links to your failing runs so we can see logs.

**Comment by igorbiscanin** [comment]
Attaching logs:

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.
* What went wrong:
Task 'jacocoTestReport' not found in root project 'xxx'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org


BUILD FAILED in 2s
##[error]The process '/home/runner/work/xxx/gradlew' failed with exit code 1

##[error]🚨 Coverage run failed!

(node:2998) UnhandledPromiseRejectionWarning: Error: The process '/home/runner/work/xxx/gradlew' failed with exit code 1

    at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v2.5.7/node_modules/@actions/exec/lib/toolrunner.js:561:25)30
    at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v2.5.7/node_modules/@actions/exec/lib/toolrunner.js:544:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.5.7/node_modules/@actions/exec/lib/toolrunner.js:444:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

(node:2998) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:2998) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by paambaati** [comment]
@igorbiscanin This looks like a problem with how you're running `gradle` itself and not this action.

```
Task 'jacocoTestReport' not found in root project 'xxx'.
```

To help validate this, I'd recommend running your build and coverage commands sequentially as part of a separate step in your workflow and see if they all work. You can try something like this —

```yaml
- name: Step 1
  run: gradle build # Substitute this with your actual build command.
- name: Step 2
  run: grade test # Substitute this with your actual test command.
```

**Comment by igorbiscanin** [comment]
So a coverageComamnd can be skipped?

**Comment by paambaati** [comment]
@igorbiscanin Include that too and see where it fails.

**Comment by igorbiscanin** [comment]
looks like it tries to run some default command:

```
/home/runner/work/xxx/cc-reporter before-build

/usr/bin/yarn coverage

yarn run v1.22.4
error Couldn't find a package.json file in "/home/runner/work/xxx"

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

##[error]The process '/usr/bin/yarn' failed with exit code 1

##[error]🚨 Coverage run failed!

(node:4028) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/yarn' failed with exit code 1    at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v2.5.7/node_modules/@actions/exec/lib/toolrunner.js:561:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v2.5.7/node_modules/@actions/exec/lib/toolrunner.js:544:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.5.7/node_modules/@actions/exec/lib/toolrunner.js:444:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

(node:4028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:4028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by paambaati** [comment]
@igorbiscanin This tells you that `package.json` is missing.

1. Does your project have one?
2. If yes, then are you sure you're correctly using paths?

**Comment by paambaati** [comment]
Closing this as stale. Please reopen if you have more information.
