### ISSUE TITLE
Format misconfiguration did not raise error in action (silenced).

### ISSUE THREAD

**Issue by insspb** [paambaati/codeclimate-action#181]
**Describe the bug**
Error in format change does not raise error on whole action. So no error and no coverage report at destination.

**Version of `codeclimate-action` you're using**
`v2.5.7`

**Example links**
1. https://github.com/insspb/ikt/pull/29/checks?check_run_id=700546967

**Expected behavior**
Should fail globally, as it is error in configuration.

**Comment by paambaati** [comment]
Should be fixed in the latest [`v2.7.0`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.7.0) release.
