### ISSUE TITLE
Set the 'prefix' parameter and the action fails

### ISSUE THREAD

**Issue by Alelho** [paambaati/codeclimate-action#185]
**Describe the bug**
I sent the test reporter to the code climate, but I got this error message below:

> {
  "message": "Invalid path part \"/\" and Invalid path part \"/\"",
  "file_document": "{\"_id\"=>BSON::ObjectId('5ed3c6b842ab182246002132'), \"type\"=>\"test_file_reports\", \"blob_id\"=>\"3750e50900cfbc331b3518fb087c02bfee33a964\", \"coverage\"=>\"[null,null,null,null,null,null,null,null,4,4,0,0,0,null,null,4,null,4,0,0,null,null,4,null,4,null,null,1,1,null,1,null,1,1,null,1,null,0,0,null,0,null,1,1,null,1,null,0,0,null,0,null,1,1,null,1,null,0,0,null,4,null,null,0,null,null,null,4,0,null,4,null,4,null,null,null,null,null,null,null,4,null,0,null,4]\", \"covered_percent\"=>60, \"covered_strength\"=>1.5, \"line_counts\"=>{\"missed\"=>16, \"covered\"=>24, \"total\"=>40}, \"path\"=>\"/home/runner/work/warren-global-portfolio/warren-global-portfolio/src//Warren.Global.Portfolio.Converters/Common/PercentageConverter.cs\", \"test_report_id\"=>BSON::ObjectId('5ed3c6b8fe05c221d3003109')}"
}

I written to the 'codeclimate' support and they tell me that I should turn the path into a relative path using the prefix parameter.

I've tried to do this in my yml file:
![image](https://user-images.githubusercontent.com/24500247/83360355-16e7e580-a357-11ea-8634-a62f6e0a9e17.png)

When I included the prefix parameter I receive this error for the action:

![image](https://user-images.githubusercontent.com/24500247/83360396-75ad5f00-a357-11ea-8527-2a7219418238.png)

**Version of `codeclimate-action` you're using**
`v2.6.0`

**Expected behavior**
I don't know if my config is wrong or if has a bug when putting the prefix parameter. Maybe you could help me with this question.

**Comment by CCFenner** [comment]
@Alelho the message says `Invalid path part "/" and Invalid path part "/"`, the trailing `//` in your prefix doesn't look correct. Try removing one `/`.

**Comment by paambaati** [comment]
@Alelho If the recommendation from @CCFenner didn't work, please reopen.
