### ISSUE TITLE
Running 'Test and Publish Code Coverage' returns a TypeError message

### ISSUE THREAD

**Issue by Fiyin-Anne** [paambaati/codeclimate-action#224]
**Describe the bug**
I am trying to send the test report to code-climate. After running the job, it says the step passed but on opening it, it only contains error messages. 

`(node:7164) UnhandledPromiseRejectionWarning: TypeError: (s || "").replace is not a function
    at escapeData (D:\a\_actions\paambaati\codeclimate-action\v2.5.6\node_modules\@actions\core\lib\command.js:66:10)
    at Command.toString (D:\a\_actions\paambaati\codeclimate-action\v2.5.6\node_modules\@actions\core\lib\command.js:60:35)
    at issueCommand (D:\a\_actions\paambaati\codeclimate-action\v2.5.6\node_modules\@actions\core\lib\command.js:23:30)
    at Object.issue (D:\a\_actions\paambaati\codeclimate-action\v2.5.6\node_modules\@actions\core\lib\command.js:27:5)
    at Object.error (D:\a\_actions\paambaati\codeclimate-action\v2.5.6\node_modules\@actions\core\lib\core.js:127:15)
    at D:\a\_actions\paambaati\codeclimate-action\v2.5.6\lib\main.js:85:20
    at Generator.throw (<anonymous>)
    at rejected (D:\a\_actions\paambaati\codeclimate-action\v2.5.6\lib\main.js:6:65)
(node:7164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I also get the same result after using the `v2.6.0` and `v2.5.7` versions.

**Version of `codeclimate-action` you're using**
`v2.5.6`

**Example links**
[Github action](https://github.com/devcareer/code-jammers-backend/pull/26/checks?check_run_id=1090834779)

**Expected behavior**
It should run successfully and send the test report to Code climate.

**Comment by paambaati** [comment]
@Fiyin-Anne Can you try this out with the latest [`v2.7.0`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.7.0) version? It has better reporting and should help you pinpoint the issue.

**Comment by hitmands** [comment]
neither `2.7.0`, nor `2.7.1` seem to execute the coverage command at all... 

<img width="1021" alt="Screenshot 2020-09-28 at 14 36 50" src="https://user-images.githubusercontent.com/5674833/94439273-1f7eea00-0198-11eb-95d2-7b3ad8521390.png">

**Comment by paambaati** [comment]
@hitmands I've just now pushed a new release - please try [`v2.7.2`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.7.2).

**Comment by tetienne** [comment]
Sorry to up this issue, but I have exactly the same behavior: https://github.com/tetienne/somfy-open-api/runs/1510838988 
I'm using v2.7.4. The report is not uploaded to CodeClimate.

**Comment by paambaati** [comment]
@tetienne I noticed that the error in your workflow run logs is slightly different from the one reported in this issue.

To help debug your issue, can you make this change and rerun your workflow?

```diff
with:
-          coverageLocations: coverage.xml
+          coverageLocations: |
+            coverage.xml
```

**Comment by tetienne** [comment]
@paambaati Here a PR with the modification: https://github.com/tetienne/somfy-open-api/pull/67

**Comment by paambaati** [comment]
@tetienne The changes need to be merged before the action itself can kick in. In the run you linked, the CI ran with whatever's in your `master`; it needs to be merged first.
