### ISSUE TITLE
v2.7.1 stopped sending coverage comments.

### ISSUE THREAD

**Issue by dashmug** [paambaati/codeclimate-action#235]
**Describe the bug**
CodeClimate coverage comments stopped updating after upgrading. I believe there were some failures in sending the coverage data to CodeClimate.

I'm referring to this:

<img width="851" alt="Screen Shot 2020-09-28 at 10 40 00 am" src="https://user-images.githubusercontent.com/1972844/94380111-7a541980-0177-11eb-9068-18588c3da8c7.png">

Version v2.6.0 works without problems. I have reverted back to it in the mean time.

**Version of `codeclimate-action` you're using**
`v2.7.1`

**Example links**
I'll post some screenshots when I get the time.

**Expected behavior**
It will continue behaving as it was before.

**Additional context**
TODO

**Comment by bennypowers** [comment]
I experienced this as well:

https://github.com/apollo-elements/apollo-elements/runs/1189033952?check_suite_focus=true

0 seconds, no console output

**Comment by paambaati** [comment]
@bennypowers Would you mind turning on debug mode and sharing the results here? You can set the `debug` option to `true`.

**Comment by paambaati** [comment]
@dashmug The attached screenshot shows the codeclimate bot, which has nothing to do with this action. Can you help me understand how that is relevant here?

**Comment by dashmug** [comment]
@paambaati It is relevant because it means CodeClimate did not receive any coverage data so the bot isn't triggered to do anything.

**Comment by paambaati** [comment]
@dashmug Can you link me to the action run with the latest version?

**Comment by paambaati** [comment]
@dashmug @bennypowers I was able to figure out the issue and I've now pushed a new release - please try [`v2.7.2`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.7.2) and reopen this issue if the problem persists.

**Comment by dashmug** [comment]
@paambaati v2.7.2 fixed it. Thank you very much.

**Comment by bennypowers** [comment]
Thanks for the update

```
Run paambaati/codeclimate-action@v2.7.2
  with:
    coverageCommand: yarn coverage
    debug: false
  env:
    CC_TEST_REPORTER_ID: ***
/home/runner/work/apollo-elements/apollo-elements/cc-reporter before-build
/usr/bin/yarn coverage
yarn run v1.18.0
error Command "coverage" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(node:3556) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/yarn' failed with exit code 1
Error: The process '/usr/bin/yarn' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.2/node_modules/@actions/exec/lib/toolrunner.js:574:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.2/node_modules/@actions/exec/lib/toolrunner.js:557:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/paambaati/codeclimate-action/v2.7.2/node_modules/@actions/exec/lib/toolrunner.js:451:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Error: 🚨 Coverage run failed!
(node:3556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```yml
      - name: Test
        run: yarn test

      - name: Test & Publish Code Coverage
        uses: paambaati/codeclimate-action@v2.7.2
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
```
perhaps the default command should be removed?

**Comment by paambaati** [comment]
@bennypowers The default command needs to be set to an empty string in https://github.com/paambaati/codeclimate-action/blob/4a8e5772114c0297e76ab96a35b40d6df2d66bca/action.yml#L11

I'd appreciate it if you can send a PR. In the meantime, please specify a coverage command explicitly.

**Comment by bennypowers** [comment]
יאללה

PR incoming
