### ISSUE TITLE
CoveragePy Formatter not found. 

### ISSUE THREAD

**Issue by Jsyro** [paambaati/codeclimate-action#269]
**Describe the bug**
I'm attempting to use this action to report pytest results on a flask application. After the tests successfully run, the after-build job cannot find the CoveragePy package to use as a formatter. 

**Version**
`v2.7.4`

**Example links**
1. Error run with debug on https://github.com/bcgov/mines-digital-trust/runs/1533132459?check_suite_focus=true

**Expected behaviour**
coveragePY command runs the testsuite, but the `cc-test-reporter after-build` command doesn't find it. It is the supported python package by code climate. https://docs.codeclimate.com/docs/configuring-test-coverage

**Comment by paambaati** [comment]
@Jsyro the error message tells me the CodeClimate reporter cannot figure out how to format your coverage output.

Are you able to upload the coverage manually after your tests run using the CC reporter manually? You can follow the documentation — https://docs.codeclimate.com/docs/test-coverage-troubleshooting-tips

**Comment by paambaati** [comment]
@abhishekmishragithub I'd love it if you can send a PR for this!
