### ISSUE TITLE
Unexpected error during `before-build` process

### ISSUE THREAD

**Issue by dutterbutter** [paambaati/codeclimate-action#275]
**Describe the bug**
Unexpected error while running `before-build` through action. See action [logs here](https://github.com/ChainSafe/gossamer/pull/1244/checks?check_run_id=1586500798). Screen shot below of error message.

<img width="1016" alt="Screen Shot 2020-12-20 at 7 59 03 PM" src="https://user-images.githubusercontent.com/29983536/102731617-e8832500-42fd-11eb-8970-77a6e09a1fd5.png">

**Version of `codeclimate-action` you're using**
`v2.7.5`

**Example links**
1. Debug is set to true.
2. Github action [workflow here.](https://github.com/ChainSafe/gossamer/actions/runs/434776781/workflow)

**Expected behavior**
Should be able to check in without error and continue to test and upload coverage report to code climate.

**Additional context**
Was working prior to this bug.

**Comment by seongjoo-kim** [comment]
i have same error!! 
plz give me any idea

**Comment by paambaati** [comment]
Are you folks able to upload coverage manually?

**Comment by bboyle** [comment]
Also seeing this error, with v2.7.4

**Comment by dutterbutter** [comment]
Can publish manually fine using macos.

Seems to be only an issue with`ubuntu-latest`, works fine on `macos-latest`. Could be related to[ codeclimate/test-reporter/issues/449](https://github.com/codeclimate/test-reporter/issues/449) maybe?

**Comment by textbook** [comment]
I'm seeing the same thing, almost certainly caused by codeclimate/test-reporter#449. Perhaps this action could take the reporter version as an input, defaulting to "latest"?

**Comment by deivid-rodriguez** [comment]
Yay! It'd be great to be able to have a deterministic action in this regard and be able to lock the version of `test-reporter` being used under the hood :+1:.

**Comment by deivid-rodriguez** [comment]
I'm a bit buried with things now but I can try to create a PR.

**Comment by imyousuf** [comment]
Facing the same issue since today [here](https://github.com/imyousuf/webhook-broker/pull/31/checks?check_run_id=1588859227).

**Comment by deivid-rodriguez** [comment]
I created [a draft PR](https://github.com/paambaati/codeclimate-action/pull/276), it'd be nice if someone could try it since I didn't try anything myself, just edited the code.

**Comment by richardvenneman** [comment]
This might be related to https://github.com/codeclimate/test-reporter/issues/449

**Comment by dutterbutter** [comment]
Closing this now as its been fix with latest test-reporter release.
