### ISSUE TITLE
Verify the downloaded executable

### ISSUE THREAD

**Issue by mmatheson** [paambaati/codeclimate-action#331]
**Describe the bug**
No verification of the downloaded executable `test-reporter` is done. This can lead to vulnerabilities like CodeCov recently experienced: https://about.codecov.io/security-update/

**Version of `codeclimate-action` you're using**
`v2.5.7`

**Example links**

**Additional context**
https://about.codecov.io/security-update/

**Comment by beeb** [comment]
This is really paramount!

**Comment by vbersier** [comment]
The test-reporter repo was updated with instructions on how to validate the executable

https://github.com/codeclimate/test-reporter#verifying-binaries

**Comment by paambaati** [comment]
This feature has now landed in `v3.0.0`!

**Comment by vbersier** [comment]
Confirmed working! Thanks a bunch!
