### ISSUE TITLE
Unable to locate executable file cc-reporter

### ISSUE THREAD

**Issue by Mulugruntz** [paambaati/codeclimate-action#352]
**Describe the bug**
The executable file does not seem to be found on Windows environment.

**Version of `codeclimate-action` you're using**
`v2.7.5`

**Example links**
https://github.com/Mulugruntz/aiosubprocess/runs/2664633651?check_suite_focus=true#step:9:24

**Expected behavior**
It  should work, just like on macOS and linux builds.

**Additional context**
```
##[debug]ℹ️ Downloading CC Reporter from https://codeclimate.com/downloads/test-reporter/test-reporter-latest-win32-amd64 ...
##[debug]✅ CC Reporter downloaded...
Error: Unable to locate executable file: D:\a\aiosubprocess\aiosubprocess\cc-reporter. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
Error: 🚨 CC Reporter before-build checkin failed!
```

**Comment by paambaati** [comment]
@Mulugruntz The reporter isn't supported on Windows! If you'd really prefer it, please raise an issue on the CodeClimate repo; feel free to link it here.
