### ISSUE TITLE
v3.0.0 fails to load

### ISSUE THREAD

**Issue by vbersier** [paambaati/codeclimate-action#430]
**Describe the bug**
When updating the action from v2.7.5 to v3.0.0, an error is shown which prevents the task to run:

```
Download action repository 'paambaati/codeclimate-action@v3.0.0' (SHA:baef3850ca1973cd488c8c1ef005b40eb20d8f21)
Error: paambaati/codeclimate-action/v3.0.0/action.yml:
Error: paambaati/codeclimate-action/v3.0.0/action.yml: (Line: 30, Col: 51, Idx: 902) - (Line: 30, Col: 80, Idx: 931): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load paambaati/codeclimate-action/v3.0.0/action.yml
```

**Version of `codeclimate-action` you're using**
`v3.0.0`

**Expected behavior**
Same as v2.7.5

**Comment by marcospassos** [comment]
Same problem here.

**Comment by paambaati** [comment]
Folks, thanks for reporting this. v3 hasn’t been published on the marketplace yet!

Although the release tag has been pushed, it isn’t available on the Marketplace for some reason. I’m taking to GitHub support about this.

**Comment by paambaati** [comment]
Got a response from GitHub Support –

> Hi GP,
>
> Thank you for reaching out to GitHub Support and sorry to hear you've experienced this issue.
> I've opened up an internal issue for the Actions team to investigate. I'll write back once I hear from them.
>
> Cheers,
> GitHub Support
