### ISSUE TITLE
Reporter checksum does not match

### ISSUE THREAD

**Issue by marcospassos** [paambaati/codeclimate-action#509]
**Describe the bug**
All our repos suddenly stopped working with the error:
![image](https://user-images.githubusercontent.com/943036/156461830-f0922ff0-40ca-4f0f-9e76-4d04dcad267a.png)

**Version of `codeclimate-action` you're using**
`v3.0.0`

**Comment by marcospassos** [comment]
Code Climate is down. That's probably the cause of the checksum mismatch.

**Comment by paambaati** [comment]
@marcospassos Can you confirm this is still the case?

**Comment by marcospassos** [comment]
I can confirm that Codeclimate's outage caused it.
