### ISSUE TITLE
Consider deleting the 2.7.1 release

### ISSUE THREAD

**Issue by joshhayes-sheen-vt** [paambaati/codeclimate-action#533]
**Describe the bug**

The 2.7.1 release had a bug that basically cause it to silently no-op https://github.com/paambaati/codeclimate-action/issues/235

This bug was fixed in the next version, but the 2.7.1 action is still available for use, and can trip folks using old documentation or who upgraded to that version and didn't notice that their reports became outdated

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#deleting-a-release

This may cause a surge of bug reports or broken builds, but imo (As someone who doesn't have to hear them, admittedly) that's preferable to the silent failures that could be happening now

**Version of `codeclimate-action` you're using**
`v2.7.1`

**Example links**

**Expected behavior**

**Additional context**

**Comment by ThomasKoppensteiner** [comment]
Given the comments in https://github.com/paambaati/codeclimate-action/issues/316#issuecomment-1077713806 and the issue described in #532 I'm wondering which version should be used.

**Comment by paambaati** [comment]
You should be using the latest v3.0.0 version – that is also documented in the README. If the latest stable version is not working, please raise a bug.
