### ISSUE TITLE
Deprecation warnings on CI

### ISSUE THREAD

**Issue by edouard** [paambaati/codeclimate-action#621]
**Describe the bug**
We’re getting deprecation warnings on CI due to outdated dependencies on paambaati/codeclimate-action.

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It looks like #612 would fix this deprecation warning.

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: paambaati/codeclimate-action

It looks like changing this line to using node 16 would fix this deprecation warning:

https://github.com/paambaati/codeclimate-action/blob/0cfced9415b7021e2247f0e6412cf075c20a71ca/action.yml#L33

**Version of `codeclimate-action` you're using**
`v3.0.0`

**Comment by paambaati** [comment]
This is now fixed and available in v3.1.0. Thanks @edouard for reporting and @fabn for sending a PR!

**Comment by edouard** [comment]
It looks like it fixed it. Thanks!
