### ISSUE TITLE
GitHub Actions failing with: File not found: '/home/runner/work/_actions/paambaati/codeclimate-action/v3.1.0/lib/main.js'

### ISSUE THREAD

**Issue by edouard** [paambaati/codeclimate-action#626]
Since about an hour ago, the CodeClimate step of our GitHub action fails with `File not found: '/home/runner/work/_actions/paambaati/codeclimate-action/v3.1.0/lib/main.js'`

We're running `paambaati/codeclimate-action@v3.1.0`

**Comment by edouard** [comment]
We’ve rerun actions that previously succeeded and they now fail, so it probably has to do with the [latest commits pushed to the repo today](https://github.com/paambaati/codeclimate-action/commits/main)?

**Comment by paambaati** [comment]
@edouard I've just published v3.1.1, can you confirm that works for you?

**Comment by edouard** [comment]
@paambaati Yup, it works for me now with v3.1.1. Thank you for fixing it so quickly!

**Comment by paambaati** [comment]
Apologies, and thanks for confirming.

To anyone else stumbling into this issue, I'm very sorry that I broke existing workflows. Please upgrade to v3.1.1 to continue using this action.

```diff
- uses: paambaati/codeclimate-action@v3.1.0
+ uses: paambaati/codeclimate-action@v3.1.1
```

**Comment by edouard** [comment]
No problem. Would it help existing users using `codeclimate-action` version < 3.1.1 if you pushed a `master` branch in interim?

**Comment by paambaati** [comment]
@edouard Unfortunately, no. I've tried this too, but the error continues to show up – see https://github.com/paambaati/codeclimate-action/actions/runs/3295541744/jobs/5434208601

For now, unfortunately, the only recourse is to upgrade the action to > v3.1.1.

**Comment by Dejavue1980** [comment]
codeclimate-action``
