### ISSUE TITLE
Incorrect branch and sha sent to Code Climate when workflow triggered by `pull_request_target` event

### ISSUE THREAD

**Issue by mattseddon** [paambaati/codeclimate-action#627]
**Describe the bug**

When a PR workflow is triggered by the `pull_request_target` event (required for sending secrets to forked repositories) the action sends the incorrect SHA + Branch details to Code Climate, which results in the coverage being posted on the target branch PR. It seems like the issue is here:

https://github.com/paambaati/codeclimate-action/blob/8788c820257f80343c47eb820a5f1cd9763e3faf/src/main.ts#L38

The line needs to be extended to include `pull_request_trigger`: 

```typescript
  if (
    process.env.GITHUB_EVENT_NAME &&
    ['pull_request', 'pull_request_target'].includes(
      process.env.GITHUB_EVENT_NAME
    )
  ) {
    env.GIT_BRANCH = process.env.GITHUB_HEAD_REF || env.GIT_BRANCH; // Report correct branch for PRs (See https://github.com/paambaati/codeclimate-action/issues/86)
    env.GIT_COMMIT_SHA = context.payload.pull_request?.['head']?.['sha']; // Report correct SHA for the head branch (See https://github.com/paambaati/codeclimate-action/issues/140)
  }

```

**Version of `codeclimate-action` you're using**
`v3.1.1`

**Example links**

Coverage for this PR: https://github.com/iterative/vscode-dvc/pull/2645
Reported here: https://github.com/iterative/vscode-dvc/pull/2644#issuecomment-1286149204

**Expected behavior**

Coverage is reported on the correct PR for workflows triggered by `pull_request_target`.

**Additional context**
Seems related to the exact problems shown in https://github.com/paambaati/codeclimate-action/issues/86 & See https://github.com/paambaati/codeclimate-action/issues/140

I have forked the repository and made the appropriate changes locally. Would be happy to raise a PR if you let me know the basics of contributing to this repository (do I need to update the changelog, semver, etc?) 🙏🏻.

**Comment by 0x2b3bfa0** [comment]
E.g.
```yaml
env:
  GITHUB_EVENT_NAME: ${{ github.event_name == 'pull_request_target' && 'pull_request' || github.event_name }}
```
