### ISSUE TITLE
Clean up generated files

### ISSUE THREAD

**Issue by YunaBraska** [paambaati/codeclimate-action#639]
**Describe the bug**
This github action adds files to the repositiry which should be deleted after run. I always checking code climate files as i am updating my project in my pipelines

**Version of `codeclimate-action` you're using**
`v3.2.0`

**Example links**
* 1 [`Manual removing cc files`](https://github.com/YunaBraska/java-info-action/commit/e71e3433bc9000f05f70d12acb73b9856ca50285)
* 2  [`auto commit added cc files`](https://github.com/YunaBraska/java-info-action/commit/d5b8921c49b6672665bcb5fe64a749b0b768ca5c)
* 3 [`workflow file`](https://github.com/YunaBraska/java-info-action/blob/main/.github/workflows/publish.yml#L68)

**Expected behavior**
No changes on the repository

**Additional context**
N/A

**Comment by paambaati** [comment]
Marking this as an enhancement/feature request rather than a bug, as this isn't a guarantee that the Action makes anyway.

I will be fixing this in a follow-up PR soon though.
