### ISSUE TITLE
could we add windows support?

### ISSUE THREAD

**Issue by bboyle** [paambaati/codeclimate-action#665]
**Is your feature request related to a problem? Please describe.**

This action currently checks the platform and blocks on windows.

CodeClimate say "Test Reporter tool now available for Windows" https://codeclimate.com/changelog/7dd79ee1cf1af7141b2bd18b
so maybe it's possible to easily support windows?

**Describe the solution you'd like**

I would like to run this action on windows.

**Describe alternatives you've considered**

Other codeclimate coverage reporter actions don't seem as full-featured (especially collecting multiple coverage reports from a monorepo).

Running the actions on linux caused other integration issues.
The cost of running my automated tests on linux is higher than on windows (linux minutes are cheaper on github, but the tests take so much longer to run that the net cost is higher).

**Additional context**

If this is something I can help with, let me know. I can see where the windows platform checks are but don't know if it's as simple as removing them, or if more is required. I'm not familiar with creating github actions.

**Comment by bboyle** [comment]
that's an unusual choice by code climate 😅 I was planning to run it in a github action, so depends what github run here. Not sure if I can specify the CPU architecture but will find out (and send feedback to codeclimate if it's an issue).

**Comment by paambaati** [comment]
Weekend update – I think I have it ready to run on Windows, except for an unexplained issue where tests are failing on CI alone.

I've raised it here – https://github.com/ljharb/tape/issues/593

**Comment by bboyle** [comment]
I see how much work you're doing on it, thanks!

**Comment by paambaati** [comment]
Please hold on while I fix my broken release process; raised at https://github.com/semantic-release/semantic-release/discussions/2788

**Comment by paambaati** [comment]
@bboyle I was finally able to land this after a break from employment. Let me know if this works!

**Comment by bboyle** [comment]
sadly I don't have an easy way to test this now — my company shifted to a self-hosted gitlab. was looking forward to trying this out, I got a lot of great use from this codeclimate action while we were on github. thank you! I hope this windows release helps another dev
