### ISSUE TITLE
CC Reporter GPG signature verfication failed!

### ISSUE THREAD

**Issue by mattseddon** [paambaati/codeclimate-action#690]
The action has just started failing to verify the CC reporter GPG signature due to a request to https://keys.openpgp.org/vks/v1/by-fingerprint/9BD9E2DD46DA965A537E5B0A5CBF320243B6FD85 timing out.

![image](https://github.com/paambaati/codeclimate-action/assets/37993418/7b6f74d3-543d-4fe2-9aa8-0015c4bbbed9)

Example runs: 
- https://github.com/iterative/vscode-dvc/actions/runs/6008003065/attempts/1
- https://github.com/iterative/vscode-dvc/actions/runs/6008003065/attempts/2
- https://github.com/iterative/vscode-dvc/actions/runs/6008003065/job/16295147630?pr=4585

Using: `v5.0.0`

Seems similar to https://github.com/paambaati/codeclimate-action/issues/656

**Comment by paambaati** [comment]
You can temporarily turn this off by setting `verifyDownload: false` – see https://github.com/paambaati/codeclimate-action#inputs
