### ISSUE TITLE
Run paambaati/codeclimate-action@v4.0.0 Error: File not found: '/home/runner/work/_actions/paambaati/codeclimate-action/v4.0.0/lib/main.js'

### ISSUE THREAD

**Issue by amindadgar** [paambaati/codeclimate-action#721]
**Describe the bug**
I'm getting the error below while trying to use the `paambaati/codeclimate-action@v4.0.0` in my GitHub workflow (It was working fine on Friday 3 days ago).

```
Run paambaati/codeclimate-action@v4.0.0
Error: File not found: '/home/runner/work/_actions/paambaati/codeclimate-action/v4.0.0/lib/main.js'
```

**Version of `codeclimate-action` you're using**
`v4.0.0`

**Example links**
The specific link I'm getting the error is https://github.com/TogetherCrew/broker-lib-py/actions/runs/7151934175/job/19508111559?pr=50

**Expected behavior**
CodeClimate should get the coverage report and just upload it simply to codeClimate.

**Comment by bpb27** [comment]
upgrading to 5.0.0 works:

```yml
uses: paambaati/codeclimate-action@v5.0.0
```

appears that the 4.0.0 package is looking for `main.js` but the package only has a `main.ts`

**Comment by amindadgar** [comment]
Thanks. upgrading to 5.0.0 worked. closing the issue now
