### ISSUE TITLE
As the v5 got released, v4 broke

### ISSUE THREAD

**Issue by rogerluan** [paambaati/codeclimate-action#722]
**Describe the bug**

As the v5 was released a few days ago, v4 broke. See: https://github.com/rogerluan/arkana/pull/54

**Version of `codeclimate-action` you're using**
`v4.0.0`

**Example links**

https://github.com/rogerluan/arkana/actions/runs/7187532885/job/19575296052

**Expected behavior**

Since I haven't changed anything on my end, I'd expect everything to continue working until I decide to upgrade to v5 😅

**Comment by paambaati** [comment]
Unfortunately, the underlying workflow (based on semantic-release) is broken, and the only option is to upgrade. I'm terribly sorry for this unexpected and rude change, but I did not expect or plan for the release to break in this way.

FWIW, I'm also attempting to fix this workflow for good so I don't break future releases – see https://github.com/paambaati/codeclimate-action/issues
