### ISSUE TITLE
Update from Node.js 16 to Node.js 20

### ISSUE THREAD

**Issue by cyri113** [paambaati/codeclimate-action#731]
**Is your feature request related to a problem? Please describe.**

When you run this action, we are now getting the following warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: paambaati/codeclimate-action@v5.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Describe the solution you'd like**

Update the action to use Node.js 20.

**Comment by paambaati** [comment]
The action can easily upgrade to Node 20, but currently the release process is broken and I'm afraid of pushing a new release that can break older ones. Any help here would be appreciated – see https://github.com/semantic-release/semantic-release/discussions/2788

**Comment by JuanVqz** [comment]
Hi @paambaati, I may be wrong on the issue you are referring to sematic release but I think you can specify the next version to release, including it in the release commit or in the PR release this: `Release-As: 0.1.1` 

![image](https://github.com/paambaati/codeclimate-action/assets/7331511/ec4e2df9-1f90-493f-8f77-2ce7fe15cf34)
https://github.com/JuanVqz/noko_cli/commits/main/

**Comment by Fryguy** [comment]
@paambaati Reading https://github.com/semantic-release/semantic-release/discussions/2788 it looks like you were able to solve the problem, but then you asked for help here?  I'm a little confused, but would love to help out.

**Comment by paambaati** [comment]
I've started working on this, and I think I have a working solution. I do not have access to my personal machine at the moment, so expect the fix to go live in a week's time.

[release-please.patch](https://github.com/paambaati/codeclimate-action/files/15071498/release-please.patch)

I will be applying this patch and releasing v6 that should hopefully stop breaking future releases.
