### ISSUE TITLE
Make coverageCommand optional

### ISSUE THREAD

**Issue by jcubic** [paambaati/codeclimate-action#797]
**Is your feature request related to a problem? Please describe.**

I have a setup when I already have unit tests run and the coverage files are already created. I don't need to execute anything in order to collect coverage.

**Describe the solution you'd like**
coverageCommand should be optional

**Describe alternatives you've considered**

**Additional context**

**Comment by paambaati** [comment]
@jcubic As a workaround, you can use a noop command that does nothing.

**Comment by jcubic** [comment]
I've checked the code, and it looks that it's optional.

https://github.com/paambaati/codeclimate-action/blob/main/src/main.ts#L283-L297
