### ISSUE TITLE
Coverage report doesn't seem to be reported for pull requests

### ISSUE THREAD

**Issue by libre-man** [paambaati/codeclimate-action#86]
I think this is related to #42, as the `GITHUB_REF` environment variable is something else than is expected in the code. Here is the documentation for the environment variables and their value when the action runs for a pull request: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request

**Comment by paambaati** [comment]
@libre-man Thanks for reporting; can you turn on debugging with `debug: true` and then paste the output here?

**Comment by libre-man** [comment]
Sure, here is the output of a run with debug set to true: https://pipelines.actions.githubusercontent.com/UPnQIIdR7GsnLGuVExRBQ5d7xkAF3CK3ENMoNtQpumuxcInF1l/_apis/pipelines/1/runs/1210/signedlogcontent/3?urlExpires=2020-01-12T14%3A56%3A17.5147160Z&urlSigningMethod=HMACV1&urlSignature=fAFbQKVb8WVNlPKbVnWq13a87NPz2RuxEXf%2FqHXrKg0%3D

**Comment by paambaati** [comment]
@libre-man Terribly sorry, but I’ve been unexpectedly busy and looks like the pipeline has expired. I plan to look at this and try to fix this tomorrow, so it’d be great if you can run it again and share the output.

**Comment by partydrone** [comment]
I'm also seeing this issue. It looks like the branch name is not reported correctly. It looks like the branch name reported by the action is for the pull request, not the git branch:

<img width="1518" alt="Screen Shot 2020-02-18 at 10 38 11 AM" src="https://user-images.githubusercontent.com/57892/74764255-9e916480-523e-11ea-8c9c-3b34bfee42e6.png">

Here is the relevant bit from my [Action logs](https://gist.github.com/partydrone/2216aa07e1d4728aedd1250a4b1113d2).

**Comment by paambaati** [comment]
@libre-man @partydrone I've just pushed [`v2.5.1`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.5.1) with a fix for this. Feel free to reopen this issue if it doesn't work.
