### ISSUE TITLE
Does not work on Windows images

### ISSUE THREAD

**Issue by peterdanis** [paambaati/codeclimate-action#98]
Hi, currently CodeClimate support only Linux and OS X (https://docs.codeclimate.com/docs/configuring-test-coverage#section-locations-of-pre-built-binaries). Please mention that in the readme file and throw an undestandable error in the code.

Related: https://github.com/codeclimate/test-reporter/issues/419

**Comment by paambaati** [comment]
@peterdanis Fixed in [`v2.5.2`](https://github.com/paambaati/codeclimate-action/releases/tag/v2.5.2).
